[package]
name = "komodo_periphery"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[[bin]]
name = "periphery"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# local
komodo_client.workspace = true
periphery_client.workspace = true
environment_file.workspace = true
environment.workspace = true
interpolate.workspace = true
secret_file.workspace = true
formatting.workspace = true
transport.workspace = true
encoding.workspace = true
command.workspace = true
config.workspace = true
logger.workspace = true
cache.workspace = true
noise.workspace = true
git.workspace = true
# mogh
serror = { workspace = true, features = ["axum"] }
async_timing_util.workspace = true
derive_variants.workspace = true
resolver_api.workspace = true
# external
hickory-resolver.workspace = true
serde_yaml_ng.workspace = true
futures-util.workspace = true
tokio-stream.workspace = true
portable-pty.workspace = true
shell-escape.workspace = true
axum-server.workspace = true
urlencoding.workspace = true
serde_json.workspace = true
tokio-util.workspace = true
arc-swap.workspace = true
colored.workspace = true
tracing.workspace = true
bollard.workspace = true
sysinfo.workspace = true
dotenvy.workspace = true
anyhow.workspace = true
rustls.workspace = true
bytes.workspace = true
serde.workspace = true
shlex.workspace = true
tokio.workspace = true
axum.workspace = true
clap.workspace = true
envy.workspace = true
uuid.workspace = true
